"""Initial migration

Revision ID: fb3ce47cb958
Revises: 
Create Date: 2019-10-28 17:27:05.849695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3ce47cb958'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USER',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('hashed_password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_USER_email'), 'USER', ['email'], unique=True)
    op.create_index(op.f('ix_USER_username'), 'USER', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_USER_username'), table_name='USER')
    op.drop_index(op.f('ix_USER_email'), table_name='USER')
    op.drop_table('USER')
    # ### end Alembic commands ###
